<a href="https://colab.research.google.com/github/tarangga/Learn-Advanced-Tensorflow/blob/main/Learn_Advanced_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.add([1, 2], [3, 4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [3]:
tf.square([4, 9.0])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([16., 81.], dtype=float32)>

In [4]:
help(tf.reduce_sum)

Help on function reduce_sum in module tensorflow.python.ops.math_ops:

reduce_sum(input_tensor, axis=None, keepdims=False, name=None)
    Computes the sum of elements across dimensions of a tensor.
    
    This is the reduction operation for the elementwise `tf.math.add` op.
    
    Reduces `input_tensor` along the dimensions given in `axis`.
    Unless `keepdims` is true, the rank of the tensor is reduced by 1 for each
    of the entries in `axis`, which must be unique. If `keepdims` is true, the
    reduced dimensions are retained with length 1.
    
    If `axis` is None, all dimensions are reduced, and a
    tensor with a single element is returned.
    
    For example:
    
      >>> # x has a shape of (2, 3) (two rows and three columns):
      >>> x = tf.constant([[1, 1, 1], [1, 1, 1]])
      >>> x.numpy()
      array([[1, 1, 1],
             [1, 1, 1]], dtype=int32)
      >>> # sum all the elements
      >>> # 1 + 1 + 1 + 1 + 1+ 1 = 6
      >>> tf.reduce_sum(x).numpy()
      

In [5]:
tf.reduce_sum([[1, 2, 3], [2, 5, 0]])

<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [6]:
tf.multiply([
             [1, 2, 3],
             [-1, -2, -3]
], [0, -1, 3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 0, -2,  9],
       [ 0,  2, -9]], dtype=int32)>

In [7]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [8]:
tf.random.uniform([3, 3]).device.endswith('GPU:0')

True

In [9]:
tf.matmul(
    [
     [1, 2],
     [2, 3]
    ], [
        [-1, -2, -3],
        [-3, -4, -6]
    ]
)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ -7, -10, -15],
       [-11, -16, -24]], dtype=int32)>

In [10]:
tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

<TensorSliceDataset shapes: (), types: tf.int32>

In [11]:
# Create a CSV file
import tempfile
_, filename = tempfile.mkstemp()
filename = "temp.txt"
print(filename)
with open(filename, 'w') as f:
  f.write("""Line 1
Line 2
Line 3
  """)

temp.txt


In [12]:
tf.data.TextLineDataset(filename)

<TextLineDatasetV2 shapes: (), types: tf.string>

In [13]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [14]:
layer = tf.keras.layers.Dense(2, input_shape = (None, 2))

In [15]:
layer.variables

[]

In [16]:
tf.ones([1, 2])

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 1.]], dtype=float32)>

In [17]:
layer(tf.ones([1, 2]))

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.8582662,  1.3088229]], dtype=float32)>

In [18]:
tf.add(0.9136654 , 0.9305545)

<tf.Tensor: shape=(), dtype=float32, numpy=1.8442199>

In [19]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(MyDenseLayer, self).__init__()
    self.num_outputs = num_outputs
  
  def build(self, input_shape):
    self.kernel = self.add_weight('kernel',
                                  shape=[int(input_shape[-1]),
                                  self.num_outputs]
                                  )
  def call(self, inputs):
    return tf.matmul(inputs, self.kernel)

MyDenseLayer(10)(tf.ones([10, 5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[-0.07258028,  1.7646511 , -0.29071388, -1.430393  ,  0.6263229 ,
        -0.54074395, -1.2006335 ,  0.8489835 , -0.0183025 , -0.36031783],
       [-0.07258028,  1.7646511 , -0.29071388, -1.430393  ,  0.6263229 ,
        -0.54074395, -1.2006335 ,  0.8489835 , -0.0183025 , -0.36031783],
       [-0.07258028,  1.7646511 , -0.29071388, -1.430393  ,  0.6263229 ,
        -0.54074395, -1.2006335 ,  0.8489835 , -0.0183025 , -0.36031783],
       [-0.07258028,  1.7646511 , -0.29071388, -1.430393  ,  0.6263229 ,
        -0.54074395, -1.2006335 ,  0.8489835 , -0.0183025 , -0.36031783],
       [-0.07258028,  1.7646511 , -0.29071388, -1.430393  ,  0.6263229 ,
        -0.54074395, -1.2006335 ,  0.8489835 , -0.0183025 , -0.36031783],
       [-0.07258028,  1.7646511 , -0.29071388, -1.430393  ,  0.6263229 ,
        -0.54074395, -1.2006335 ,  0.8489835 , -0.0183025 , -0.36031783],
       [-0.07258028,  1.7646511 , -0.29071388, -1.430393  ,  0.62632

In [34]:
class ResnetBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetBlock, self).__init__(name='')
    filters1, filters2, filters3 = filters

    self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()

    self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
    self.bn2b = tf.keras.layers.BatchNormalization()

    self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()

  def call(self, input_tensor, training=False):
    out = self.conv2a(input_tensor)
    out = self.bn2a(out, training=training)
    out = tf.nn.relu(out)

    out = self.conv2b(out)
    out = self.bn2b(out, training=training)
    
    out = self.conv2c(out)
    out = self.bn2c(out, training=training)
    
    out = out + input_tensor
    return tf.nn.relu(out)

block = ResnetBlock(1, [1, 2, 3])

block(tf.ones([1, 2, 3, 3]))

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0.63524044, 1.570189  , 0.83011454],
         [0.63524044, 1.570189  , 0.83011454],
         [0.63524044, 1.570189  , 0.83011454]],

        [[0.63524044, 1.570189  , 0.83011454],
         [0.63524044, 1.570189  , 0.83011454],
         [0.63524044, 1.570189  , 0.83011454]]]], dtype=float32)>