<a href="https://colab.research.google.com/github/tarangga/Learn-Advanced-Tensorflow/blob/main/Learn_Advanced_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [3]:
tf.add([1, 2], [3, 4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [7]:
tf.square([4, 9.0])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([16., 81.], dtype=float32)>

In [9]:
help(tf.reduce_sum)

Help on function reduce_sum in module tensorflow.python.ops.math_ops:

reduce_sum(input_tensor, axis=None, keepdims=False, name=None)
    Computes the sum of elements across dimensions of a tensor.
    
    This is the reduction operation for the elementwise `tf.math.add` op.
    
    Reduces `input_tensor` along the dimensions given in `axis`.
    Unless `keepdims` is true, the rank of the tensor is reduced by 1 for each
    of the entries in `axis`, which must be unique. If `keepdims` is true, the
    reduced dimensions are retained with length 1.
    
    If `axis` is None, all dimensions are reduced, and a
    tensor with a single element is returned.
    
    For example:
    
      >>> # x has a shape of (2, 3) (two rows and three columns):
      >>> x = tf.constant([[1, 1, 1], [1, 1, 1]])
      >>> x.numpy()
      array([[1, 1, 1],
             [1, 1, 1]], dtype=int32)
      >>> # sum all the elements
      >>> # 1 + 1 + 1 + 1 + 1+ 1 = 6
      >>> tf.reduce_sum(x).numpy()
      

In [12]:
tf.reduce_sum([[1, 2, 3], [2, 5, 0]])

<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [22]:
tf.multiply([
             [1, 2, 3],
             [-1, -2, -3]
], [0, -1, 3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 0, -2,  9],
       [ 0,  2, -9]], dtype=int32)>

In [2]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
tf.random.uniform([3, 3]).device.endswith('GPU:0')

True

In [7]:
tf.matmul(
    [
     [1, 2],
     [2, 3]
    ], [
        [-1, -2, -3],
        [-3, -4, -6]
    ]
)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ -7, -10, -15],
       [-11, -16, -24]], dtype=int32)>

In [9]:
tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

<TensorSliceDataset shapes: (), types: tf.int32>

In [13]:
# Create a CSV file
import tempfile
_, filename = tempfile.mkstemp()
filename = "temp.txt"
print(filename)
with open(filename, 'w') as f:
  f.write("""Line 1
Line 2
Line 3
  """)

temp.txt


In [15]:
tf.data.TextLineDataset(filename)

<TextLineDatasetV2 shapes: (), types: tf.string>

In [18]:
tf.test.is_gpu_available()

True

In [30]:
layer = tf.keras.layers.Dense(2, input_shape = (None, 2))

In [35]:
layer.variables

[<tf.Variable 'dense_2/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[ 0.9136654 , -0.73422575],
        [ 0.9305545 ,  0.8993901 ]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]

In [36]:
tf.ones([1, 2])

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 1.]], dtype=float32)>

In [34]:
layer(tf.ones([1, 2]))

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1.8442199 , 0.16516435]], dtype=float32)>

In [38]:
tf.add(0.9136654 , 0.9305545)

<tf.Tensor: shape=(), dtype=float32, numpy=1.8442199>